title:        'terrcin'
tagline:      'stuff of interest'
description:  ''
url:          http://terrcin.github.io
author:       
  name:       'Nahum Wild'
  email:      'nahum.wild@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
